### PR TITLE
Offline version

### PR DESCRIPTION
**Pull request by jacobbogers**
HI created offline version  and also manifest file for mobile install

### CODE REVIEW

**Review by dfahlander — COMMENTED** [review]
Thanks a lot for this improvement!

I will have a deeper look and test it in weekend.

**Comment by jacobbogers** [comment]
I noticed a small bug if there is no explict `.html` extention like `http://localhost:4000/docs/Dexie/Dexie.on.populate`  the cache gets confused, let me fix that

**Review by dfahlander — COMMENTED** [review]
Why is CNAME renamed to _CNAME?
CNAME is the file that maps dexie.org to this site

**Review by dfahlander — COMMENTED** [review]
When I served jekyll locally, and launched chrome debugger, I could only see deleted service workers and on page reload, there were errors from service worker (served from localhost:4000).

**Comment by jacobbogers** [comment]
I was trying to run it  on git-hubpages pages repo, so i tinkered with CNAM
It was interesting exercise,  i cant use addAll because if one of the url fales for some reason it will just stop , so i do it one by one with "cache.put",  I will parallelize it with caching 10 urls at a time, for now it works there is a thing with  rerouting 302
`http://unpkg.com/dexie -> https://unpkg.com/dexie -> https://unpkg.com/dexie@2.0.4``
Prolly wrap it up tomorrow

**Comment by jacobbogers** [comment]
Hi, I think its working now, i cant load  `http://www.google-analytics.com/analytics.js`, thats the only url that cannot be cached while testing from localhost:4000, maybe it will be different if comes from dexie domain. I cant test that
Let me know how it is working for you, it was very interesting for me to do this ticket

**Comment by jacobbogers** [comment]
@dfahlander
I normally work with Jira (your comment `Manual review, change and merge of #40`) i dont fully understand , there is not much at line 40 or something. Jira always shows line specific annotations of reviewers, or maybe i am doing something wrong.

**Comment by dfahlander** [comment]
Ok thanks a lot! :) The "Manual review ..." was just a commit I made in another branch (were merging your changes in command line and modifying the result, as I don't want the other changes that was included (frontpage changes except the sw inclusion, CNAME rename).

I'll do another try next weekend to retest/review/merge your latest changes.

**Comment by jacobbogers** [comment]
Hi just some notes
I think there are some inconsistencies in markdown links and the  files jekyll scripts tells it has,

Here are some examples: 

_I use localhost:4000 as **origin** reference in the links below so its easy to replicate on localhost_

- on the page: `http://localhost:4000/docs/Collection/Collection.eachUniqueKey()` there is a non-working link to `http://localhost:4000/docs/Promise/Promise.then()`. Thats because the "then" documentation is missing (I checked)
- on the page: `http://localhost:4000/docs/` page there is a markdown link (line 12) `[Tutorial](/docs/Tutorial)` this should be chaned to   **note the forward slash at the end** `[Tutorial](/docs/Tutorial/)`

I know there is an nginx and apache setting to ignore leading forward slash '/' in urls, so github has configured this to be like that, 

So the choice is either to duplicate this (make it '/' agnostic) or correct all the links in the markdowns to add the '/' when needed. 

What do you think?

**Comment by jacobbogers** [comment]
I made the offline agnostic regardless if you are requesting `/docs` or `/docs/` (example) but only for local uris (non-local uris will not be checked for ending ´/´)

Let me know if all is ok there are some missing links in the docs, as I am reading your docs, I will encounter them, thanks for making this great lib

**Comment by jacobbogers** [comment]
Shall i make an "read offline" button, so people can decide to optionally install it locally? or do you think this is oj for now?

**Comment by jacobbogers** [comment]
Hi @dfahlander, what do you think about PR so far?

**Comment by dfahlander** [comment]
Thanks for fixing it and for this reminder. I haven't forgotten it but unfortunately I havent got the time to review it yet. I hope to have that time in next weekend.

**Comment by jacobbogers** [comment]
no worries, dfahlandler, I got many irons in the fire aswell, ))

**Comment by jacobbogers** [comment]
Hi  @dfahlander , have you had time to run it?,  should take much time as I double checked every link in the docs, I tested it locally with a 'http-server' npm module, works like a charm

**Comment by dfahlander** [comment]
@jacobbogers I want to merge this PR, but I am having issues with the changes that includes stuff that is not related to the offline capability. For example the landing page is changes - samples looks slightly different. I am trying to fix this myself within another PR, but if I get stuck or so, you could help me by removing all your changes from index.html that is not directly needed to invoke the sw.

**Comment by jacobbogers** [comment]
Can you be more explicit or give an example?
As far as i can see i only added this  (see snippet below) in index.html it is surely needed to install  the service worker for offline
```html
<script type="text/javascript">
		if ('serviceWorker' in navigator) {
			navigator.serviceWorker.register('/sw.js').then(function (registration) {
				console.log('Service Worker registration successful with scope: ', registration.scope);
			}).catch(function (err) {
				console.log('Service Worker registration failed: ', err);
			});
		}
	</script>
```html

**Comment by jacobbogers** [comment]
As far as i can see i only added this  (see snippet below) in index.html it is surely needed to install  the service worker for offline, the rest of the html i didnt touch (as you check with `git diff`)
Can you give one example of what "looks slightly different"?
```html
<script type="text/javascript">
		if ('serviceWorker' in navigator) {
			navigator.serviceWorker.register('/sw.js').then(function (registration) {
				console.log('Service Worker registration successful with scope: ', registration.scope);
			}).catch(function (err) {
				console.log('Service Worker registration failed: ', err);
			});
		}
	</script>

```

**Review by dfahlander — APPROVED** [review]
Thanks for removing the spacing changes etc from index.html. The diff looks much better now.

**Pull request merged**
