### PR TITLE
Various small changes

### PR DESCRIPTION
**Pull request by garcialo**
- Best Practices: Mostly annoyed I missed a misspelling, so fixing that since I already had the repo forked
- Navbar: Adding some alt attributes to images lacking them in navbar
- Navbar: Changed "Who use Dexie?" to "Who uses Dexie?" and "Github Desktop" to "GitHub Desktop"
- Navbar: Added label to the offline toggle switch input
- Added lang="en" to <html>
- Regretting having clicked "Edit on GitHub," but glad to contribute a little bit to something that's helped me not have to touch IndexedDB directly

### CODE REVIEW

**Comment by garcialo** [comment]
...I'm not sure why it has all the previous commits as well. Is that normal?

**Comment by dfahlander** [comment]
> ...I'm not sure why it has all the previous commits as well. Is that normal?

If you merge from upstream and push again, I think they will disappear.

```
git merge upstream/master
git push
```

**Comment by garcialo** [comment]
I've tried doing that and I keep getting feedback that everything is up-to-date. Well I get errors with master/main, but not with the default branch. To be more clear...

```
git merge upstream/master
merge: upstream/master - not something we can merge

git merge upstream/main
merge: upstream/main - not something we can merge

git merge upstream/gh-pages
Already up to date.

git push
Everything up-to-date
```

I primarily use github.com/GitHub Desktop, I made sure that my fork was synced, and fetched locally to make sure everything was in the same state before this PR. The page for my fork still shows...

```
This branch is not behind the upstream dfahlander:gh-pages
No new commits to fetch. Enjoy your day!
```

I'll look into this more a little later today and see what I can find.

**Comment by dfahlander** [comment]
Ah, your right, the main branch in this repo is "gh-pages". No problem that the old commits are there - the total changes only show the last ones. To get rid of the changes in future commits I think you can rebase your fork from the upstream:

```
git rebase upstream/gh-pages
git push --force
```

**Comment by dfahlander** [comment]
Regarding the changes - they're really great!

**Pull request merged**
