### PR TITLE
Initial commit to move docs from wiki

### PR DESCRIPTION
**Pull request by nponiros**
index.html remained pretty much the same but the docs button points to the docs on dexie.org.

Added wiki pages under the docs folder and split them a bit into folders based on their file name. For example docs referencing the Table class are in the Table folder under docs.

Added front-matter to all docs pages.

Added docs template to render a docs page. Also a few style fixes for the docs pages and a new prism css which is a bit closer to the one offered by github. I think the dark theme is a bit too dark for docs.

Todos:

- [x] Fix all URLs in the docs pages (hopefully I didn't miss anything)
- [ ] Merge latest changes from the Dexie wiki (up to date as of 05/02 12:30 CET)
- [x] Add links in the Wiki pages to the new docs (prepare locally, push after the docs are online)
- [x] Link back to the home page from the docs page
- [ ] Better integrate the home page with the docs page (no ideas for that now)
- [x] Code highlight all code blocks
- [ ] Add analytics to doc pages (if needed)
- [x] Better sorting for the side bar (sort alphabetically)
- [x] Typescript/HTML code highlighting
- [x] Update READMEs which reference wiki pages (PR: https://github.com/dfahlander/Dexie.js/pull/470)
- [ ] Adjust structure of doc page (1) (maybe this should be moved to ideas for later)

(1) Regarding the structure of a doc page. I took the Building-Addons.html page as example and adjusted the layout a bit. The title of the page (currently the file  name) is a H1 and the headings in the content start from H2 and go smaller when needed. Currently there are pages starting with h2 others with h3, I would like to adjust that so all start with h2. The other change I made was to define a subtitle to come before the first h2. This is just a short text which many pages have. I just put it in its own place to make it for the user easier to understand in one sentence what the function etc. does. The screenshot illustrates what I described.

dexie_docs_page

@dfahlander If you are okay with the new layout, I will adjust all the wiki pages as shown in the screenshot. We would also have to coordinate the merge of the latest wiki changes so we don't lose anything.

Ideas for later:

* Maybe split docs into API/for developers/Tutorial/etc.
* Maybe have a navbar (in docs/home) referencing API/for developers/Tutorial etc.
* Maybe a separate page to list the addons and derived work as part of the nav
* Improve design
* Maybe add deprecations/version notices and similar as front-matter attributes with a predefined position/color in the template

### CODE REVIEW

**Comment by dfahlander** [comment]
@nponiros thanks! I can merge in the evening or tomorrow latest

**Comment by nponiros** [comment]
@dfahlander cool. Better to merge fast, because merging new changes from the wiki also costs time. The rest (like structural changes) can be done later. It took me ~8 hours just to adjust the links. Changing the structure will take at least as much time. Adding analytics is simple. Just add it to default.html and maybe the analytics key to head.html.

Just give me a heads up so I can push the wiki changes linking to dexie.org.

**Comment by dfahlander** [comment]
Merged it in and fixed the EDIT links (for non-index pages)

**Comment by nponiros** [comment]
Cool thanks. Couldn't really test that and didn't realize that the links are broken

**Comment by dfahlander** [comment]
@nponiros I added you as collaborator to dexie.js-web in case you would want to push directly for typos etc.

**Comment by nponiros** [comment]
@dfahlander okay thanks. I will push the wiki changes with links to the new docs tonight

**Comment by dfahlander** [comment]
Great. I also locked down the wiki so that it's not open for public editing anymore (only collaborators). If possible, it would be great if at least [this page](https://github.com/dfahlander/Dexie.js/wiki/Dexie.PrematureCommitError) links directly to the new location of the same page. It is referred to when a the exception is thrown in code as http://bit.ly/2eVASrf. I also think that API Reference should link directly to http://dexie.org/docs/API-Reference.html.

**Comment by nponiros** [comment]
All wiki pages link to their counter-part on dexie.org so no issues there. Only WritableTable/WritableCollection point to Collection/Table pages.

**Comment by nponiros** [comment]
So I pushed the wiki. Everything looks good to me

**Pull request merged**
