### PR TITLE
Structured navigation for docs

### PR DESCRIPTION
**Pull request by raphinesse**
This addresses #10 by structuring the navigation in the docs similarly as to how the corresponding files were structured in the repo itself. No URLs should have changed in the process. Here's a shortened preview:

dexie-web_new-nav

I'd say the result is far from perfect but still way better than the status quo and could serve as a starting point for further work.

### CODE REVIEW

**Comment by dfahlander** [comment]
Thanks a lot 👍  An improvement indeed.
I tried the PR locally though and got some strange structure. Updated jekyll to latest and still the same. Header comes last and is indented, but the first un-indented line is one of the sub-pages, see screen-shot:

image

**Comment by raphinesse** [comment]
Strange indeed. Might be a locale/collation issue.

Right now, items are sorted by title and the first one is taken as header. With the possibility to set `index: yes` on an item to make it rise above all others. Apart from `DexieError`, all groups take the former approach, since it conveniently worked for me that way.

Implementation: [list sorting], [header extraction].

- What locale are you using on your system?
Try running `locale` on Linux
- Does the sorting order change if you run with a different locale?
Try running `env LC_ALL=C bundle exec jekyll serve` on Linux
- Is `DexieError` the header of its group?

[list sorting]: https://github.com/raphinesse/dexie.js-web/blob/040cab0fbebf394b1351660bc6f2aa4dcbca1e85/_layouts/docs.html#L48-L49
[header extraction]: https://github.com/raphinesse/dexie.js-web/blob/040cab0fbebf394b1351660bc6f2aa4dcbca1e85/_includes/nav-index.html#L4-L11

**Comment by raphinesse** [comment]
After looking at this again, it actually does not seem like a collation issue at all. The funny thing is that first and last entry seem to be switched. I don't see how that should happen and unfortunately, I cannot reproduce it on my end. Neither when using the bundled gem versions, nor when using the latest gem versions.

Are you using the included `start.sh` or `bundle exec jekyll serve` to serve the site? The former might use any gem versions on your system, while the latter makes sure to actually use the versions specified in `Gemfile.lock`. At least that's how I remember it from my ruby adventures from a few years ago :sweat_smile:

**Comment by dfahlander** [comment]
Closing this as it seems to be stale.

**Pull request closed without merging**
