### PR TITLE
To replace #40 Offline version

### PR DESCRIPTION
**Pull request by dfahlander**
Since #40 contains changes in the front page structure, used to have renamed the CNAME file etc, I needed to make sure to pick out only the relevant changes of PR #40 and not just merge in it as is, because it would be a risk for the dexie.org page stop working or linking to suspicious content.

So this PR basically is a cherry pick of #40.

### CODE REVIEW

**Comment by dfahlander** [comment]
Oops. Seems I got all changes in index.html in. Need to go through index.html again and remove all changes that are not directly connected to the offline version. Then I might merge this in.

**Comment by jacobbogers** [comment]
As far as i can see i only added this  (see snippet below) in index.html it is surely needed to install  the service worker for offline, the rest of the html i didnt touch (as you check with `git diff`)
Can you give one example of what "looks slightly different"?
```html
<script type="text/javascript">
		if ('serviceWorker' in navigator) {
			navigator.serviceWorker.register('/sw.js').then(function (registration) {
				console.log('Service Worker registration successful with scope: ', registration.scope);
			}).catch(function (err) {
				console.log('Service Worker registration failed: ', err);
			});
		}
	</script>

```

**Comment by jacobbogers** [comment]
OK I copy old index.html and copy pasted the  install code for the service worked and pushed 
Check if it is all ok

**Comment by jacobbogers** [comment]
I have updated my PR,

**Comment by dfahlander** [comment]
Closing as the original #40 was updated.

**Pull request closed without merging**
