### PR TITLE
Repeat the fact that updatedObj is passed to onsuccess

### PR DESCRIPTION
**Pull request by ariofrio**
So that its front and center at the top instead of buried. This imitates the convention used in the creating hook.

Related: https://github.com/dfahlander/Dexie.js/pull/670

### CODE REVIEW

**Review by dfahlander — CHANGES_REQUESTED** [review]
Thanks! We will though have to explain somewhere that the new behavior will be from in version 3.0

**Comment by ariofrio** [comment]
Were you planning on merging this and publishing the docs before 3.0 is released (i.e. "in the upcoming 3.0 release"? Or just a backwards-compatibility notice (i.e. "in versions before 3.0")?

Also, did you want to reference the issue for context about why behavior was different before?

**Review by dfahlander — APPROVED** [review]

**Comment by dfahlander** [comment]
I just reminded myself this was just in line with the docs, so the PR can be accepted right away instead.

**Comment by dfahlander** [comment]
I merged your commit into master-2 branch and released a 2.0.2 version with the same fix.

**Pull request merged**
